services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - frontend
      - kuma
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma-https.tls=true
      - traefik.http.routers.uptime-kuma-https.tls.certresolver=cloudflare
      - traefik.http.routers.uptime-kuma-https.entrypoints=websecure
      - traefik.http.routers.uptime-kuma-https.rule=Host(`kuma.caradev.fr`)
      - traefik.http.services.uptime-kuma-https.loadBalancer.server.port=3001

volumes:
  kuma-data:
    name: kuma-data

networks:
  frontend:
    external: true
  kuma:
    external: true
