services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/etc/traefik:ro
      - traefik-certs:/var/traefik/certs/:rw
    networks:
        - frontend
        - secure_frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.caradev.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.middlewares=allow-vpn-only@file"

volumes:
  traefik-data:
    name: traefik-data
  traefik-certs:
    name: traefik-certs

networks:
  frontend:
    external: true
  secure_frontend:
    external: true
